# Backup location to teleport prisoner on unjail if location before jailed is found corrupt.
backupLocation:
  world: world
  x: 0.0
  y: 0.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0

# Counts offline time as sentence time.
offlineTime: false

# Change prisoner group when jailed.
# Needs Vault to be installed.
changeGroup: false
# Group name for prisoner to be moved to when jailed.
prisonerGroup: prisoner

# Automatically save prisoners and jails data files.
# Set to 0 to disable.
autoSaveTimeInMinutes: 5

# Messages shown.
messages:
  # Placeholders for /jail:
  # · {prisoner}: player to be jailed.
  # · {player}: player that executes the command.
  # · {jail}: jail name to where the prisoner will be sent.
  # · {time}: time argument provided.
  jailSuccess: "&c{prisoner} &6has been jailed by &c{player} &6for &c{time}&6."
  jailFailedPlayerNeverJoined: "&cPlayer &4{prisoner} &cnever joined this server."
  jailFailedPlayerExempt: "&4{prisoner} &ccannot be jailed."
  # Placeholders for /jail info:
  # · {prisoner}: player to retrieve the status and info.
  # · {player}: player that executes the command.
  infoFailedPlayerNotJailed: "&6The player you are requesting the information from is not currently serving a sentence."

  # Generic error messages when resolving a jail or prisoner for a command.
  # Available placeholders:
  # · {jail}: non-existent jail attempted to resolve.
  non-existent-jail: "&cJail &4{jail} &cdoesn't exist"
  # · {prisoner}: non-existent prisoner attempted to resolve.
  player-not-imprisoned: "&4{prisoner} &cis not imprisoned"

  # Placeholders for /unjail:
  # · {prisoner}: player to be unjailed.
  # · {player}: player that executes the command.
  unjailSuccess: "&c{prisoner} &6has been unjailed by &c{player}&6."
  unjailFailedPlayerNotJailed: "&c{prisoner} &6could not be unjailed, player wasn't jailed."

  # Placeholders for /setjail and /deljail:
  # · {player}: player that executes the command.
  # · {jail}: jail name to be added/removed.
  setjailSuccess: "&6Jail added successfully!"
  save-jail-failed: "&cAn error occurred while saving data for jail &4{jail}&c. Check the console for errors."
  deljailSuccess: "&6Jail removed successfully!"
  delete-jail-failed: "&cAn error occurred while deleting data for jail &4{jail}&c. Check the console for errors."

  # Placeholders for /betterjails reload and /betterjails save:
  # · {player}: player that executes the command.
  reload: "&6Files reloaded successfully!"
  reload-failed: "&cAn error occurred while reloading plugin data. Check the console for errors."
  save: "&6Files saved successfully!"
  save-all-failed: "&cAn error occurred while saving plugin data. Check the console for errors."

  # Placeholders for /jails premessages:
  # · None :(
  listNoJails: "&6There are no jails available!"
  listJailsPremessage: "&6Available jails:"

  # Placeholders for /jails list:
  # · None :(
  jailsFormat: "line"

  # jailsFormat can be any of these values:
  # · list
  # · line
  #
  # Examples:
  #   list:
  #     · jail1
  #     · jail2
  #     · jail3
  #   line:
  #     jail1, jail2, jail3.
