name: "BetterJails"
author: "emilyy-dev"
version: "${version}"
main: "io.github.emilyydev.betterjails.BetterJailsPlugin"
api-version: "1.13"
softdepend: [ "Essentials", "Vault", "LuckPerms" ]

permissions:
  betterjails.jail: { }
  betterjails.jail.exempt: { }
  betterjails.jails: { }
  betterjails.unjail: { }
  betterjails.setjail: { }
  betterjails.deljail: { }
  betterjails.receivebroadcast: { }
  betterjails.betterjails:
    default: "true"
  betterjails.betterjails.reload: { }
  betterjails.betterjails.save: { }
