name: "BetterJails"
author: "emilyy-dev"
version: "${version}"
main: "io.github.emilyydev.betterjails.BetterJailsPlugin"
api-version: "1.13"
softdepend: [ "Essentials", "Vault", "LuckPerms" ]

commands:
  jail:
    permission: "betterjails.jail"
    usage: "§cUsage: /jail <player> <jail> <time>\n§cUsage: /jail info <player>"
    description: "Sends a player to the provided jail, and won't be teleported back until they spend online the time provided."
  jails:
    permission: "betterjails.jails"
    usage: "§cUsage: /jails"
    description: "Prints a list of available jails."
  unjail:
    permission: "betterjails.unjail"
    usage: "§cUsage: /unjail <player>"
    description: "Teleports a jailed player back to where they were when jailed."
  setjail:
    permission: "betterjails.setjail"
    usage: "§cUsage: /setjail <jailname>"
    description: "Adds a new jail location in where the command is executed."
  deljail:
    permission: "betterjails.deljail"
    usage: "§cUsage: /deljail <jailname>"
    description: "Removes a jail location from the jails list."
  betterjails:
    permission: "betterjails.betterjails"
    description: "Prints the version of the plugin."

permissions:
  betterjails.jail: { }
  betterjails.jail.exempt: { }
  betterjails.jails: { }
  betterjails.unjail: { }
  betterjails.setjail: { }
  betterjails.deljail: { }
  betterjails.receivebroadcast: { }
  betterjails.betterjails:
    default: "true"
  betterjails.betterjails.reload: { }
  betterjails.betterjails.save: { }
